### PR TITLE
Edit profile page, payment history, particular site, remove tenant charges all completed

### LINKED ISSUE #47: Integrate edit profile page with change password modal

### LINKED ISSUE #55: Watch Payment history for each site
On the particular site page you have to display all the transaction for the particular site.

### LINKED ISSUE #56: Watch payment history for all the site
You have to display all the charges data for all the sites created by the landlord  on a single page by summing every month and total changes

### PR DESCRIPTION
**Pull request by anuj1511**

### CODE REVIEW

**Comment by anuj1511** [comment]
It is incomplete for now, just copied the code from tenant
Now updating the code

**Comment by rishabhborn2win** [comment]
Ok

**Comment by anuj1511** [comment]
By mistake the particular site page is also pushed to this pr

**Comment by anuj1511** [comment]
SIr its the similar error like in tenant, there is some export error for the format function

**Comment by anuj1511** [comment]
I am not able to solve this error, I tried different ways to export but different errors occured

**Comment by rishabhborn2win** [comment]
Ok else everything is completed?

**Comment by anuj1511** [comment]
All things completed, only on clicking on details user should go to charges details page that page is left

**Pull request merged**
