### PR TITLE
Create Site page

### LINKED ISSUE #16: create site page

### LINKED ISSUE #26: template of react context api setup
add the store in the project

### LINKED ISSUE #27: Integrate signup and signin routes with the frontend

### PR DESCRIPTION
**Pull request by anuj1511**

### CODE REVIEW

**Comment by rishabhborn2win** [comment]
@anuj1511 remove the vercel deployment error and there are some conflicts in the PR so remove those conflicts

Screenshot 2022-01-10 at 7 40 14 PM

**Comment by rishabhborn2win** [comment]
@anuj1511 the PR you create has vercel deployment error + conflicting file so see that

**Comment by anuj1511** [comment]
sir these conflict in in trace and package lock in which I am facing problems, I will try to resolve them

**Comment by anuj1511** [comment]
Completed signin part and removed all conflicts

**Comment by anuj1511** [comment]
Sir you may remove the landlord integration branch, facing some problems to merge changes there

**Pull request merged**
